import { Roboto_Condensed, Bebas_Neue, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const roboto = Roboto_Condensed({ subsets: ["latin"], weight: ["100", "900"] });
const bebas = Bebas_Neue({ subsets: ["latin"], weight: ["400"] });
const space = Space_Grotesk({ subsets: ["latin"], weight: ["300", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-white">
      <body
        className={`${bebas.className} ${space.className} ${roboto.className} antialiased`}
      >
        <div className="container mx-auto">{children}</div>
        <Toaster />
      </body>
    </html>
  );
}
